"""Add brand_id to product

Revision ID: a98af4d49fd9
Revises: 92a70131ee0e
Create Date: 2025-03-20 10:43:59.730154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98af4d49fd9'
down_revision = '92a70131ee0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_brand', 'brand', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###
